import constants from 'react-constants';

export default constants([
    'BOOKMARK_RELATED_CONTENT',

    'VISIT_RELATED_CONTENT',

    'GET_RELATED_CONTENT_REQUEST',
    'GET_RELATED_CONTENT_SUCCESS',
    'GET_RELATED_CONTENT_ERROR',

    'LOAD_MORE_RELATED_CONTENT_REQUEST',
    'LOAD_MORE_RELATED_CONTENT_SUCCESS',
    'LOAD_MORE_RELATED_CONTENT_ERROR',

    'SEARCH_RELATED_CONTENT_REQUEST',
    'SEARCH_RELATED_CONTENT_SUCCESS',
    'SEARCH_RELATED_CONTENT_ERROR',

    'RESET_SEARCH_RELATED_CONTENT'
]);
