export const BOOKMARK_PAGE = 'BOOKMARK_PAGE';
export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const VISIT_ITEM = 'VISIT_ITEM';
export const LOAD_MORE_RELATED_CONTENT = 'LOAD_MORE_RELATED_CONTENT';
