import constants from 'react-constants';

export default constants([
    'DISABLE_FOR_THIS_PAGE',
    'DISABLE_FOR_THIS_WEBSITE',
    'ENABLE',
    'GET_DISABLED_STATE',
    'BOOKMARK_RELATED_CONTENT',
    'SET_PAGE_SELECTED',
    'SET_PAGE_FILTER',
    'GET_RELATED_CONTENT_REQUEST',
    'GET_RELATED_CONTENT_SUCCESS',
    'GET_RELATED_CONTENT_ERROR'
]);
