Fonts:
  PT Sans:
    name: "PT Sans"
    slug: "PT-Sans"

      regular:
        name: "Regular"
        font-weight: "400"

      bold:
        name: "Bold"
        font-weight: "700"

Format: "woff"
